version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dynoecomdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpostgresdb
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      PGDATABASE: dynoecomdb
      PGUSER: postgres
      PGPASSWORD: localpostgresdb
      PGHOST: db
      PGPORT: 5432
    depends_on:
      - db
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
